project:
  type: website
  resources:
    - "images/front-page-crop1.jpg"
    - "images/banner_DJI_0568_colour-enhanced_cropped.jpg"

website:
  title: "AIMS eReefs Visualisation Portal"
  favicon: images/ereefs_logo_favicon.svg
  search: true
  navbar:
    title: "eReefs Visualisations"
    logo: https://www.ereefs.org.au/assets/images/logos/ereefs_logo.svg
    background: light
    pinned: false
    right:
      - href: https://www.ereefs.org.au/
        text: Home
      - text: About
        menu:
          - href: https://www.ereefs.org.au/about/
            text: About eReefs
          - href: about.qmd
            text: About AIMS eReefs
      - href: https://www.ereefs.org.au/research/
        text: Research
      - href: https://www.ereefs.org.au/tools/
        text: Tools
      - href: https://www.ereefs.org.au/contact/
        text: Contact
      - text: Help
        menu:
          - href: help/index.qmd
            text: Visualisation Portal Help
          - href: https://open-aims.github.io/ereefs-tutorials/
            text: Tutorials
          - href: https://extraction.ereefs.aims.gov.au/faqs
            text: Data Extraction FAQs
  page-footer:
    background: primary
    center:
      - text: Collaborators
        href: https://www.ereefs.org.au/about/collaborators.html
      - text: Funders
        href: https://www.ereefs.org.au/about/funders.html
      - text: Privacy Policy
        href: https://www.csiro.au/en/About/Access-to-information/Privacy
      - text: Legal & Disclaimer
        href: https://www.csiro.au/en/about/Policies/Legal/Legal-notice
  sidebar:
    style: "floating"
    search: true
    pinned: true
    collapse-level: 3
    contents:
      - section: "Products"
        contents:
          - section: "Hydrodynamic Model"
            contents:
              - section: "GBR1"
                contents:
                  - text: "Temperature, wind, salinity and current"
                    href: /gbr1/temp-wind-salt-current/
                  - text: "Temperature at 2.35m, 18m and 49m depth"
                    href: /gbr1/temp-multi-depth/
                  - text: "Current at 2.35m, 18m and 103m depth"
                    href: /gbr1/current-multi-depth/
                  - text: "Salinity at 2.35m, 5.35m and 18m depth"
                    href: /gbr1/salt-multi-depth/
                  - text: "Fresh water exposure at 2.35m"
                    href: /gbr1/fresh-water-exposure/
                  - text: "Current magnitude average at 2.35m"
                    href: /gbr1/current-magnitude-average/
                  - text: "Temperature range at 2.35m"
                    href: /gbr1/temp-range/
                  - text: "Flood plume extents for major rivers on GBR based on modelled river tracers"
                    href: /gbr1/river-tracers/
              - section: "GBR4 v4.0 2010-10 - 2022-11"
                contents:
                  - text: "Temperature, wind, salinity and current"
                    href: /gbr4_v4/temp-wind-salt-current/
                  - text: "Temperature at 1.5m, 18m and 49m depth"
                    href: /gbr4_v4/temp-multi-depth/
                  - text: "Current at 1.5m, 18m and 103m depth"
                    href: /gbr4_v4/current-multi-depth/
                  - text: "Temperature range at 1.5m"
                    href: /gbr4_v4/temp-range/
                  - text: "Comparing eReefs (GBR4 temperature, current) to IMOS satellite temperature and ocean current"
                    href: /gbr4_v4/imos-vs-ereefs/
              - section: "GBR4 v2.0 2022-11 - 2023-12"
                contents:
                  - text: "Temperature, wind, salinity and current"
                    href: /gbr4/temp-wind-salt-current/
                  - text: "Temperature at 1.5m, 18m and 49m depth"
                    href: /gbr4/temp-multi-depth/
                  - text: "Current at 1.5m, 18m and 103m depth"
                    href: /gbr4/current-multi-depth/
                  - text: "Temperature range at 1.5m"
                    href: /gbr4/temp-range/
                  - text: "Comparing eReefs (GBR4 temperature, current) to IMOS satellite temperature and ocean current"
                    href: /gbr4/imos-vs-ereefs/
          - section: "BioGeoChemical Model (4 km)"
            contents:
              - section: "Water chemistry"
                contents:
                  - text: "Total alkalinity, PH & Aragonite saturation state"
                    href: /gbr4/bgc/baseline/alk_ph_omega-ar/
                  - text: "Dissolved inorganic nitrogen, nitrate & ammonia"
                    href: /gbr4/bgc/baseline/din_no3_nh4/
                  - text: "Dissolved oxygen & oxygen saturation percentage"
                    href: /gbr4/bgc/baseline/oxygen_oxy-sat/
                  - text: "Dissolved Inorganic (Carbon, Nitrogen & Phosphorus)"
                    href: /gbr4/bgc/baseline/din_dip_dic/
                  - text: "Dissolved Organic (Carbon, Nitrogen & Phosphorus)"
                    href: /gbr4/bgc/baseline/dor-c_dor-n_dor-p/
                  - text: "Particulate inorganic phosphorus & particulate inorganic"
                    href: /gbr4/bgc/baseline/pip_pip-sed/
              - section: "Water quality measures"
                contents:
                  - text: "Total chlorophyll, dissolved inorganic nitrogen & total suspended solids"
                    href: /gbr4/bgc/baseline/chl-a-sum_din_efi/
                  - text: "Total Suspended Solids, dust, mud carbonate & mud mineral"
                    href: /gbr4/bgc/baseline/efi_dust_mud-carbonate_mud-mineral/
                  - text: "Secchi depth, vertical attenuation at 490nm & light intensity above seagrass"
                    href: /gbr4/bgc/baseline/secchi_kd-490_epipar-sg/
                  - text: "Simulated true colour"
                    href: /gbr4/bgc/baseline/true-colour/
              - section: "Macroalgae, seagrass and coral"
                contents:
                  - text: "Coral symbiont (nitrogen & chlorophyll) & coral host nitrogen"
                    href: /gbr4/bgc/baseline/cs-n_cs-chl_ch-n/
                  - text: "Nitrogen (macroalgae, seagrass zostera, seagrass halophila & deep seagrass)"
                    href: /gbr4/bgc/baseline/ma-n_sg-n_sgh-n_sgd-n/
              - section: "Catchment scenarios comparison"
                contents:
                  - text: "Disolved inorganic nitrogen"
                    href: /gbr4/bgc/scenarios/din
                  - text: "Total Chlorophyll"
                    href: /gbr4/bgc/scenarios/chl-a-sum
                  - text: "Secchi depth"
                    href: /gbr4/bgc/scenarios/secchi
                  - text: "Total suspended solids"
                    href: /gbr4/bgc/scenarios/efi
                  - text: "Light intensity above seagrass"
                    href: /gbr4/bgc/scenarios/epipar-sg

format:
  html:
    theme:
      - css/custom.scss
    css:
      - css/ereefs_aims.css
      - css/ncanimate2.css
      - css/ncanimate2_responsive.css
      - css/styles.css
    toc: false
    include-in-header:
      - text: <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700" rel="stylesheet">
      - text: <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto" rel="stylesheet">
      - includes/_google_analytics.html
      - includes/_page_banner.html
    grid:
      body-width: 1000px
    mainfont: Open Sans
    fontcolor: "#212529"

execute:
  freeze: auto # ensures code blocks are only executed locally as opposed to being executes as part of GitHub actions
