function EAtlasNcAnimate2Map(htmlBlockElement,videoSelector){this.blk=htmlBlockElement;this.videoSelector=videoSelector;this.mapImg=null;this.canvas=null;this.htmlRegionList=null;this.context=null;this.width=null;this.height=null;this.hoverRegion=null;this.selectedRegion=null;this.orderedRegions=null;this.regionCache={};this.mapBBox=null;this.regionCatalogue=null;}
EAtlasNcAnimate2Map.prototype.selectRegion=function(region){if(region&&region!==this.selectedRegion){this.selectedRegion=region;this.redraw();}};EAtlasNcAnimate2Map.prototype.load=function(regionCatalogue){this.regionCatalogue=regionCatalogue;this.canvas=this.blk.find('.regionCanvas');this.htmlRegionList=this.blk.find('.regionList');this.context=null;if(this.canvas&&this.canvas.get(0)&&this.canvas.get(0).getContext){this.context=this.canvas.get(0).getContext('2d');}
var mapUrl=this.getMapURL();if(mapUrl){this.mapImg=new Image();this.mapImg.onload=(function(that){return function(){if(this.width&&this.height){that.width=this.width;that.height=this.height;}
that.loadMap();}})(this);this.mapImg.src=mapUrl;}else{this.loadMap();}};EAtlasNcAnimate2Map.prototype.loadMap=function(){var width=this.getMapWidth(),height=this.getMapHeight();if(this.context){this.context.canvas.width=width;this.context.canvas.height=height;}
this.loadRegionCache();this.populateHTMLRegionList();this.redraw();this.canvas.mousemove((function(that){return function(e){var rect=this.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;var hoverRegion=that.getRegionId(x,y);if(hoverRegion!==that.hoverRegion){if(hoverRegion){var x=window.scrollX,y=window.scrollY;that.htmlRegionList.find("a."+hoverRegion).focus();if(!isNaN(x)&&!isNaN(y)){window.scrollTo(x,y);}}else{that.htmlRegionList.find("a").focusout();}}};})(this));this.canvas.click((function(that){return function(e){var rect=this.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;var clickedRegion=that.getRegionId(x,y);if(clickedRegion!=null){eatlas_ncanimate2_set_anchor(eatlas_ncanimate2_craft_anchor({"region":clickedRegion}));that.selectRegion(clickedRegion);that.videoSelector.changeRegion(clickedRegion);}};})(this));this.canvas.mouseleave((function(that){return function(e){that.htmlRegionList.find("a").focusout();};})(this));};EAtlasNcAnimate2Map.prototype.mergeBBox=function(bbox1,bbox2){if(bbox1===null){if(bbox2===null){return null;}
return{'north':bbox2.north,'east':bbox2.east,'south':bbox2.south,'west':bbox2.west}}
if(bbox2===null){return{'north':bbox1.north,'east':bbox1.east,'south':bbox1.south,'west':bbox1.west}}
return{'north':Math.max(bbox1.north,bbox2.north),'east':Math.max(bbox1.east,bbox2.east),'south':Math.min(bbox1.south,bbox2.south),'west':Math.min(bbox1.west,bbox2.west)};};EAtlasNcAnimate2Map.prototype.getMapURL=function(){var mapBBox=this.getMapBBox(),width=this.getMapWidth(),height=this.getMapHeight();var mapUrl=this.canvas.attr('mapurl');if(!mapUrl||!mapBBox||!width||!height){return null;}
return mapUrl.replace('${NORTH}',mapBBox.north).replace('${EAST}',mapBBox.east).replace('${SOUTH}',mapBBox.south).replace('${WEST}',mapBBox.west).replace('${WIDTH}',width).replace('${HEIGHT}',height);};EAtlasNcAnimate2Map.prototype.getRegionId=function(x,y){var width=this.getMapWidth(),resizeRatio=width/this.canvas.width(),resizedX=x*resizeRatio,resizedY=y*resizeRatio;var orderedRegions=this.getOrderedRegions();for(var i=0;i<orderedRegions.length;i++){var regionId=orderedRegions[i];var regionRect=this.regionCache[regionId];if(regionRect&&resizedX>=regionRect.x&&resizedX<=regionRect.x+regionRect.width&&resizedY>=regionRect.y&&resizedY<=regionRect.y+regionRect.height){return regionId;}}
return null;};EAtlasNcAnimate2Map.prototype.loadRegionCache=function(){var orderedRegions=this.getOrderedRegions();if(this.regionCatalogue&&orderedRegions){for(var i=0;i<orderedRegions.length;i++){var regionId=orderedRegions[i];var reprojectedBBox=this.reproject(this.regionCatalogue[regionId]['bbox']);if(reprojectedBBox!==null){var regionLabel=this.regionCatalogue[regionId]['label'];var regionScale=this.regionCatalogue[regionId]['scale']||-1;if(!regionLabel){regionLabel=regionId;}
this.regionCache[regionId]={'label':regionLabel,'scale':regionScale,'x':reprojectedBBox.west,'y':reprojectedBBox.north,'width':reprojectedBBox.east-reprojectedBBox.west,'height':reprojectedBBox.south-reprojectedBBox.north};}}}};EAtlasNcAnimate2Map.prototype.populateHTMLRegionList=function(){var that=this;if(this.regionCache){var geographicallyOrderedRegions=[];for(var regionId in this.regionCache){if(this.regionCache.hasOwnProperty(regionId)){geographicallyOrderedRegions.push(regionId);}}
geographicallyOrderedRegions.sort(function(id1,id2){var region1=that.regionCache[id1],region2=that.regionCache[id2];var scale1=region1['scale']||-1;var scale2=region2['scale']||-1;var scaleDiff=scale1-scale2;if(scaleDiff!==0){return scaleDiff;}
var yCmp=region1['y']-region2['y'];if(yCmp!==0){return yCmp;}
var xCmp=region1['x']-region2['x'];if(xCmp!==0){return xCmp;}
return region1['label'].localeCompare(region2['label']);});this.htmlRegionList.empty();var lastRegionScale=null;var currentUl=null;for(var i=0;i<geographicallyOrderedRegions.length;i++){var regionId=geographicallyOrderedRegions[i];var region=this.regionCache[regionId];if(currentUl===null||region['scale']!==lastRegionScale){var scaleGroup=jQuery('<div class="regionScaleGroup"></div>')
this.htmlRegionList.append(scaleGroup);var label=(region['scale']===-1)?'Legacy regions':'Scale: '+region['scale'];scaleGroup.append(jQuery('<div class="region-scale-label">'+label+'</div>'));currentUl=jQuery('<ul></ul>');scaleGroup.append(currentUl);}
currentUl.append(jQuery(regionId===this.selectedRegion?'<li class="selected"></li>':'<li></li>').append(jQuery('<a class="'+regionId+'" href="#'+eatlas_ncanimate2_craft_anchor({"region":regionId})+'">'+region['label']+'</a>')
.mouseenter(function(){jQuery(this).focus();}).mouseleave(function(){jQuery(this).focusout();})
.focus(function(){that.hoverRegion=jQuery(this).attr("class");that.redraw();}).focusout(function(){jQuery(this).blur();that.hoverRegion=null;that.redraw();}).click(function(){var clickedRegion=jQuery(this).attr("class");eatlas_ncanimate2_set_anchor(eatlas_ncanimate2_craft_anchor({"region":clickedRegion}));})));lastRegionScale=region['scale'];}}};EAtlasNcAnimate2Map.prototype.getOrderedRegions=function(){if(this.orderedRegions===null){this.orderedRegions=[];if(this.regionCatalogue){for(var regionId in this.regionCatalogue){if(this.regionCatalogue.hasOwnProperty(regionId)){this.orderedRegions.push(regionId);}}
this.orderedRegions.sort((function(that){function getRegionArea(bbox){return(bbox.east-bbox.west)*(bbox.north-bbox.south);}
return function(id1,id2){var bbox1=that.regionCatalogue[id1]['bbox'],bbox2=that.regionCatalogue[id2]['bbox'],epsilon=0.000000001;var areaCmp=getRegionArea(bbox1)-
getRegionArea(bbox2);if(areaCmp>epsilon||areaCmp<-epsilon){return areaCmp;}
var latCmp=bbox2.north-bbox1.north;if(latCmp>epsilon||latCmp<-epsilon){return latCmp;}
return bbox2.west-bbox1.west;};})(this));}}
return this.orderedRegions;};EAtlasNcAnimate2Map.prototype.getMapBBox=function(){if(this.mapBBox===null&&this.regionCatalogue){for(var regionId in this.regionCatalogue){if(this.regionCatalogue.hasOwnProperty(regionId)){this.mapBBox=this.mergeBBox(this.mapBBox,this.regionCatalogue[regionId]['bbox']);}}
if(this.mapBBox){var mapWidthDegree=this.mapBBox.east-this.mapBBox.west,mapWidthPixel=this.getMapWidth();var degreePerPixel=mapWidthDegree/mapWidthPixel,degreePadding=20*degreePerPixel;this.mapBBox.north+=degreePadding;this.mapBBox.south-=degreePadding;this.mapBBox.east+=degreePadding;this.mapBBox.west-=degreePadding;if(this.mapBBox.north>90){this.mapBBox.north=90;}
if(this.mapBBox.south<-90){this.mapBBox.south=-90;}
if(this.mapBBox.east>180){this.mapBBox.east=180;}
if(this.mapBBox.west<-180){this.mapBBox.west=-180;}}}
return this.mapBBox;};EAtlasNcAnimate2Map.prototype.getMapWidth=function(){if(this.width===null){this.computeMapWidthHeight();}
return this.width;};EAtlasNcAnimate2Map.prototype.getMapHeight=function(){if(this.height===null){this.computeMapWidthHeight();}
return this.height;};EAtlasNcAnimate2Map.prototype.computeMapWidthHeight=function(){var mapBBox=this.getMapBBox();var desiredWidth=this.canvas.attr('mapwidth'),desiredHeight=this.canvas.attr('mapheight');var mapWidth=mapBBox.east-mapBBox.west,mapHeight=mapBBox.north-mapBBox.south;if(desiredWidth&&desiredHeight){this.width=desiredWidth;this.height=desiredHeight;}else if(desiredHeight){this.height=desiredHeight;this.width=Math.round(this.height*mapWidth/mapHeight);}else{this.width=desiredWidth?desiredWidth:200;this.height=Math.round(this.width*mapHeight/mapWidth);}};EAtlasNcAnimate2Map.prototype.redraw=function(){var width=this.getMapWidth(),height=this.getMapHeight();if(this.context){this.context.clearRect(0,0,width,height);if(this.mapImg!==null){this.context.drawImage(this.mapImg,0,0,width,height);}
this.context.strokeStyle="rgba(0, 0, 0, 0.8)";this.context.fillStyle="rgba(0, 0, 255, 0.2)";var orderedRegions=this.getOrderedRegions();if(orderedRegions){for(var i=0;i<orderedRegions.length;i++){this.drawRegion(orderedRegions[i]);}}}};EAtlasNcAnimate2Map.prototype.drawRegion=function(regionId){var rect=this.regionCache[regionId];if(this.context&&rect){if(regionId===this.selectedRegion){this.context.fillRect(rect.x,rect.y,rect.width,rect.height);}
if(regionId===this.hoverRegion){this.context.lineWidth=3;}else{this.context.lineWidth=1.5;}
this.context.strokeRect(rect.x,rect.y,rect.width,rect.height);}};EAtlasNcAnimate2Map.prototype.reproject=function(bbox){var mapBBox=this.getMapBBox(),width=this.getMapWidth(),height=this.getMapHeight();if(!mapBBox||!bbox||!width||!height){return null;}
var geoWidth=mapBBox.east-mapBBox.west;var geoHeight=mapBBox.north-mapBBox.south;var widthRatio=width/geoWidth;var heightRatio=height/geoHeight;return{'north':height-((bbox.north-mapBBox.south)*heightRatio),'east':(bbox.east-mapBBox.west)*widthRatio,'south':height-((bbox.south-mapBBox.south)*heightRatio),'west':(bbox.west-mapBBox.west)*widthRatio};};