## Source data

The videos/images on this page are based on the [4km eReefs BioGeoChemical model (v3.1) (GBR4_H2p0_B3p1_Cq3b_Dhnd,
GBR4_H2p0_B3p1_Cq3p_Dhnd, GBR4_H2p0_B3p1_Cq3R_Dhnd)](https://research.csiro.au/ereefs/models/) run with SOURCE
Catchments using Baseline, Pre-Industrial, and reduced loads (WQIP-Targets) catchment conditions. Detailed information 
about the model can be found in the paper:
[CSIRO Environmental Modelling Suite (EMS): Scientific description of the optical and biogeochemical models (vB3p0)](https://doi.org/10.5194/gmd-2019-115).

The raw model data is available from the [NCI THREDDS server](https://thredds.nci.org.au/thredds/catalog/catalogs/fx3/catalog.html) 
(daily, in curvilinear NetCDF format):  

- [GBR4 BGC Baseline scenario GBR4_H2p0_B3p1_Cq3b_Dhnd](https://dapds00.nci.org.au/thredds/catalog/fx3/gbr4_bgc_GBR4_H2p0_B3p1_Cq3b_Dhnd/catalog.html)
- [GBR4 BGC Pre-Industrial scenario GBR4_H2p0_B3p1_Cq3p_Dhnd](https://dapds00.nci.org.au/thredds/catalog/fx3/gbr4_bgc_GBR4_H2p0_B3p1_Cq3P_Dhnd/catalog.html)
- [GBR4 BGC Reduced loads (WQIP-Targets) scenario GBR4_H2p0_B3p1_Cq3R_Dhnd](https://dapds00.nci.org.au/thredds/catalog/fx3/gbr4_bgc_GBR4_H2p0_B3p1_Cq3R_Dhnd/catalog.html)

Aggregate data is available from the [AIMS eAtlas THREDDS server](https://thredds.ereefs.aims.gov.au/thredds/catalog/catalog.html)
(daily, monthly, yearly, in regular rectangular grid NetCDF format):  

- [GBR4 BGC Baseline scenario GBR4_H2p0_B3p1_Cq3b_Dhnd](https://thredds.ereefs.aims.gov.au/thredds/catalog/ereefs/GBR4_H2p0_B3p1_Cq3b_Dhnd.html)
- [GBR4 BGC Pre-Industrial scenario GBR4_H2p0_B3p1_Cq3p_Dhnd](https://thredds.ereefs.aims.gov.au/thredds/catalog/ereefs/GBR4_H2p0_B3p1_Cq3P_Dhnd.html)
- [GBR4 BGC Reduced loads (WQIP-Targets) scenario GBR4_H2p0_B3p1_Cq3R_Dhnd](https://thredds.ereefs.aims.gov.au/thredds/catalog/ereefs/GBR4_H2p0_B3p1_Cq3R_Dhnd.html)
