---
title: "How to manually download AIMS eReefs data"
---

The eReefs model data is produced by
[CSIRO](https://research.csiro.au/ereefs/) and published on the [NCI
THREDDS
server](https://dapds00.nci.org.au/thredds/catalogs/fx3/catalog.html)
(see section [Download eReefs model data from NCI THREDDS
server](#download-ereefs-model-data-from-nci-thredds-server)). For the
visualisations on this portal, the AIMS eReefs system downloads,
processes and aggregates the raw eReefs model data to provide multiple
time steps (e.g. monthly, yearly) and to transform the data from a
curvilinear to a rectilinear grid. While the curvilinear grid in the raw
eReefs model data is better suited to the modelling and execution
requirements, it can be cumbersome to process with typical data science
tools. Therefore, all eReefs derived datasets generated by the AIMS
eReefs system are regridded to a rectilinear grid.

All derived data produced by the AIMS eReefs system can be found on the
[AIMS eReefs THREDDS server](https://thredds.ereefs.aims.gov.au/). To
download the data follow these steps:

1.  Open the [AIMS eReefs THREDDS server
    website](https://thredds.ereefs.aims.gov.au/) and select the link
    [Data derived from the eReefs
    model](https://thredds.ereefs.aims.gov.au/thredds/s3catalogue/aims-ereefs-public-prod/derived/ncaggregate/ereefs/catalog.html).
2.  On the next page select the link to the required model
    1.  [GBR4_H2p0_B3p1_Cq3P_Dhnd](https://thredds.ereefs.aims.gov.au/thredds/s3catalogue/aims-ereefs-public-prod/derived/ncaggregate/ereefs/GBR4_H2p0_B3p1_Cq3P_Dhnd/catalog.html)
        := eReefs BioGeoChemical model version 3.1 (4 km resolution) -
        source catchments using **Pre-Industrial** catchment conditions
    2.  [GBR4_H2p0_B3p1_Cq3R_Dhnd](https://thredds.ereefs.aims.gov.au/thredds/s3catalogue/aims-ereefs-public-prod/derived/ncaggregate/ereefs/GBR4_H2p0_B3p1_Cq3R_Dhnd/catalog.html)
        := eReefs BioGeoChemical model version 3.1 (4 km resolution) -
        source catchments using **Hindcast** catchment conditions
        (anthropogenic loads reduced according to the percentage
        reductions of DIN, PN, PP and TSS specified in the [Reef 2050
        Water Quality Improvement Plan
        2017-2022](https://www.reefplan.qld.gov.au/__data/assets/pdf_file/0017/46115/reef-2050-water-quality-improvement-plan-2017-22.pdf))
    3.  [GBR4_H2p0_B3p1_Cq3b_Dhnd](https://thredds.ereefs.aims.gov.au/thredds/s3catalogue/aims-ereefs-public-prod/derived/ncaggregate/ereefs/GBR4_H2p0_B3p1_Cq3b_Dhnd/catalog.html)
        := eReefs BioGeoChemical model version 3.1 (4 km resolution) -
        source catchments using **Baseline** catchment conditions.
    4.  [gbr1_2.0](https://thredds.ereefs.aims.gov.au/thredds/s3catalogue/aims-ereefs-public-prod/derived/ncaggregate/ereefs/gbr1_2.0/catalog.html)
        := eReefs Hydrodynamic model version 2.0 (1 km resolution)
    5.  [gbr4_v2](https://thredds.ereefs.aims.gov.au/thredds/s3catalogue/aims-ereefs-public-prod/derived/ncaggregate/ereefs/gbr4_v2/catalog.html)
        := Reefs Hydrodynamic model version 2.0 (4 km resolution)
3.  Each model has its derived output grouped into folders with the
    names indicating the time steps and aggregation in a file. For
    example a folder with the name \"daily-monthly\" contains
    \"monthly\" files with \"daily\" data while a folder with the name
    \"annual-annual\" contains \"annual\" files with \"annual\" data.
    Select the link to the folder of interest.
4.  In the list of NetCDF files, select the one of interest. The file
    names describe the data they contain with the structure
    \"EREEFS_organisations_model_timestep-aggregation-date.nc\". For
    example the file
    \"EREEFS_AIMS-CSIRO_gbr4_v2_hydro_daily-monthly-2010-09.nc\"
    can be broken down into:\
    \"AIMS-CSIRO\" := Reference to the organisations AIMS and CSIRO\
    \"gbr4_v2_hydro\" := eReefs Hydrodynamic model version 2.0 (4 km
    resolution)\
    \"daily\" := \"daily\" data\
    \"monthly\" := one month of data\
    \"2010-09\" := data for September 2010
5.  The single file pages contain a section \"Access\". For downloading
    the NetCDF file select the link for the \"HTTPServer\"

![Example page
([EREEFS_AIMS-CSIRO_gbr4_v2_hydro_daily-monthly-2010-09.nc](http://thredds.ereefs.aims.gov.au/thredds/s3catalogue/aims-ereefs-public-prod/derived/ncaggregate/ereefs/gbr4_v2/daily-monthly/catalog.html?dataset=EREEFS_AIMS-CSIRO_gbr4_v2_hydro_daily-monthly-2010-09.nc))
indicating in yellow the "access" section and in red the link to
download the file.](./how-to-download-derived-data.png){fig-alt="A screenshot highlighting some links" .border}

# Download eReefs model data from NCI THREDDS server

Please be advised that AIMS does not manage this service and therefore
we cannot guaranty the correctness of this article.

To download the raw eReefs data follow these steps:

1.  Open the [NCI THREDDS server
    website](http://dapds00.nci.org.au/thredds/catalogs/fx3/catalog.html)
2.  Select the link to the required model
3.  In the list of NetCDF files, select the one of interest
4.  The single file pages contain a section \"Access\". For downloading
    the NetCDF file select the link for the \"HTTPServer\"

![Example page
([gbr4_simple_2016-06.nc​](http://dapds00.nci.org.au/thredds/catalog/fx3/gbr4/catalog.html?dataset=fx3-gbr4/gbr4_simple_2016-06.nc))
indicating in yellow the "access" section and in red the link to
download the file.](./how-to-download-raw-data-from-NCI.png){fig-alt="A screenshot highlighting some links" .border}
