---
title: "gbr4-bgc-baseline_din_no3_nh4"
format:
  html: 
    css: 
      - ../../../../css/css_PGbJgHCUCBf4dg7K9Kt8aAwsApndP4GZ9RuToPy3-Fk.css
      - ../../../../css/css_aspJexyZbSy-mMQCoq4YYgcmk8Ps3vDh_U10OuJIIhk.css
      - ../../../../css/css_eRVvH_jN5SStb8oQSJsiVAHkQ19dLpDrjRpGVNpiAig.css
      - ../../../../css/css_xE-rWrJf-fncB6ztZfd2huxqgxu4WO-qwma6Xer30m4.css
    template: ../../../../custom_template.html
params:
  product-name: Dissolved inorganic nitrogen, nitrate & ammonia (GBR4 BGC v3.1 baseline)
  block-name: gbr4-bgc-baseline_din_no3_nh4
  product-id: products__ncanimate__ereefs__gbr4_bgc_baseline__din_no3_nh4
---

{{< include ../../../../includes/_visualisation.qmd >}}

This visualisation shows modelled nitrogen levels from the CSIRO eReefs
Biogeochemical model. Nitrogen is a key limiting nutrient in the growth of
plants and algae. Coral reefs are generally nutrient poor environments with
much of the nutrients being locally recycled. Increased nutrient levels promote
the growth of phytoplankton, turf algae and macroalgae, inhibiting the rate of
recovery of coral reefs.

The BGC model tracks the transformation of nitrogen through the nitrogen cycle,
from fixing of nitrogen gas into ammonia by tricodesmium, to its uptake by
plants, propagation through the food chain to zooplantkon, to release due to
mortality and finally denitrification back into nitrogen gas.

The BGC model contains two forms of dissolved inorganic nitrogen (DIN),
dissolved ammonia (NH4) and dissolved nitrate (NO3): DIN = [NH4] + [NO3]. In
the model, the ammonia component of the DIN pool is assumed to be taken up
first by all primary producers (phytoplankton, tricodesmium, macroalgae and
seagrass), followed by the nitrate, with the caveat that the uptake of ammonia
cannot exceed the diffusion limit for ammonia. The underlying principle of this
assumption is that photosynthetic organisms can entirely preference ammonia,
but that the uptake of ammonia is still limited by diffusion to the organism’s
surface.

Nitrification is the oxidation of ammonia (NH4) with oxygen, to form nitrite
followed by the rapid oxidation of these nitrites into nitrates (NO3). In the
BGC model nitrification occurs in the water column and sediment depending on
oxygen levels.

Photosynthetic growth is determined by concentrations of dissolved nutrients
(nitrogen and phosphate) and photosynthetically active radiation. Autotrophs
(seagrass, phytoplankton, macroalgae and tricodesmium) take up dissolved
ammonium, nitrate, phosphate and inorganic carbon. Ammonia is preferentially
taken up as a source of nitrogen over nitrate as it can be directly used by
plants. Nitrogen is transported through the phytoplankton to zooplankton food
chain. Nitrogen is released as ammonia when an organism decays. Tricodesmium
fixes nitrogen, converting nitrogen gas N2 into ammonia NH3 when the DIN
concentration falls below a critical concentration. 

### Dissolved Inorganic Nitrogen

Concentration of dissolved inorganic nitrogen (DIN). DIN = [NH4] + [NO3].

### Nitrate

Concentration of nitrate. In the absence of nitrite [NO2-] in the model,
nitrate represents [NO3-] + [NO2-]. 

### Ammonia

Concentration of ammonia ions [NH4+].

{{< include ../../../../includes/_source_data.qmd >}}

{{< include ../../../../includes/_recent_data.qmd >}}
